// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct Book {
  var title: String? = nil
  var imageUrl: String? = nil

  static func fromList(_ list: [Any?]) -> Book? {
    let title: String? = nilOrValue(list[0])
    let imageUrl: String? = nilOrValue(list[1])

    return Book(
      title: title,
      imageUrl: imageUrl
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      imageUrl,
    ]
  }
}
private class BookApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return Book.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BookApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Book {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BookApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BookApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BookApiCodecWriter(data: data)
  }
}

class BookApiCodec: FlutterStandardMessageCodec {
  static let shared = BookApiCodec(readerWriter: BookApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BookApi {
  func searchBook(keyWord: String) throws -> [Book?]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BookApiSetup {
  /// The codec used by BookApi.
  static var codec: FlutterStandardMessageCodec { BookApiCodec.shared }
  /// Sets up an instance of `BookApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BookApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let searchBookChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_example.BookApi.searchBook\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      searchBookChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyWordArg = args[0] as! String
        do {
          let result = try api.searchBook(keyWord: keyWordArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      searchBookChannel.setMessageHandler(nil)
    }
  }
}
