// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Book;

@interface Book : NSObject
+ (instancetype)makeWithTitle:(nullable NSString *)title
    imageUrl:(nullable NSString *)imageUrl;
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * imageUrl;
@end

/// The codec used by BookApi.
NSObject<FlutterMessageCodec> *BookApiGetCodec(void);

@protocol BookApi
/// @return `nil` only when `error != nil`.
- (nullable NSArray<Book *> *)searchBookKeyWord:(NSString *)keyWord error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpBookApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BookApi> *_Nullable api);

extern void SetUpBookApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BookApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
