// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace pigeon_example {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class BookApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Generated class from Pigeon that represents data sent in messages.
class Book {
 public:
  // Constructs an object setting all non-nullable fields.
  Book();

  // Constructs an object setting all fields.
  explicit Book(
    const std::string* title,
    const std::string* image_url);

  const std::string* title() const;
  void set_title(const std::string_view* value_arg);
  void set_title(std::string_view value_arg);

  const std::string* image_url() const;
  void set_image_url(const std::string_view* value_arg);
  void set_image_url(std::string_view value_arg);


 private:
  static Book FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class BookApi;
  friend class BookApiCodecSerializer;
  std::optional<std::string> title_;
  std::optional<std::string> image_url_;

};

class BookApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  BookApiCodecSerializer();
  inline static BookApiCodecSerializer& GetInstance() {
    static BookApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class BookApi {
 public:
  BookApi(const BookApi&) = delete;
  BookApi& operator=(const BookApi&) = delete;
  virtual ~BookApi() {}
  virtual ErrorOr<flutter::EncodableList> SearchBook(const std::string& key_word) = 0;

  // The codec used by BookApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `BookApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    BookApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    BookApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  BookApi() = default;

};
}  // namespace pigeon_example
#endif  // PIGEON_MESSAGES_G_H_
